const LOCALE_STORAGE_KEY = "diamant_locale";
const DEFAULT_LOCALE = "en";
const SUPPORTED_LOCALES = ["en", "uk"];

const catalogs = {
  en: {
    "analytics.durationHours": "{hours} h {minutes} min", "analytics.durationMinutes": "{minutes} min {seconds} s", "analytics.durationSeconds": "{seconds} s", "analytics.notSpecified": "Not specified", "analytics.invalidPeriod": "The “From” date cannot be later than the “To” date.", "analytics.narrativesUnavailable": "Text metadata is temporarily unavailable.", "analytics.qualityUnavailable": "Operational metadata is temporarily unavailable.", "analytics.providersUnavailable": "Provider metadata is temporarily unavailable.", "analytics.currencyUnavailable": "Currency-source metadata is temporarily unavailable.", "analytics.adminOnly": "Analytics is available only to an administrator.", "analytics.loadFailed": "Analytics could not be loaded. Try refreshing the page later.",
    "analytics.freshnessState": "Freshness state", "analytics.latestApprovedSnapshot": "Latest approved snapshot", "analytics.candidates": "Candidates", "analytics.approvedCount": "Approved", "analytics.rejectedCount": "Rejected", "analytics.totalAttempts": "Total attempts", "analytics.scheduled": "Scheduled", "analytics.manual": "Manual", "analytics.retries": "Retries", "analytics.failedAttempts": "Failed attempts", "analytics.draftsInRange": "Drafts in range", "analytics.coveredByReference": "Covered by reference", "analytics.excludedByOrigin": "Excluded by origin", "analytics.missingCharacteristics": "Missing characteristics", "analytics.noCurrentSnapshot": "No current snapshot", "analytics.quoteNotCovered": "Quote not covered", "analytics.noValue": "None", "analytics.providerAccess": "Provider access and terms", "analytics.accessMode": "Mode", "analytics.disabled": "Disabled", "analytics.restrictedTrial": "Restricted trial", "analytics.standardInternal": "Standard internal", "analytics.notConfigured": "Not configured", "analytics.trialUntil": "Trial until", "analytics.notApplicable": "Not applicable", "analytics.dailyLimit": "Daily limit", "analytics.assignedAdministrators": "Assigned administrators", "analytics.lastPolicyChange": "Last policy change", "analytics.noPolicyEvents": "No events yet", "analytics.policyReadOnlyHelp": "This is a read-only configuration fact. Access terms can be managed only in Market data by an administrator who enabled the corresponding profile permission.", "analytics.coveredReports": "Examples of covered reports: ",
    "analytics.accountState": "Account state", "analytics.active": "Active", "analytics.inactive": "Inactive", "analytics.completedSessions": "Completed work sessions", "analytics.averageActiveSession": "Average active session", "analytics.medianActiveSession": "Median active session", "analytics.firstSaveMeasurements": "First-save measurements", "analytics.timeToFirstSave": "Time to first save", "analytics.averageTimeToFirstSave": "Average time to first save", "analytics.medianTimeToFirstSave": "Median time to first save", "analytics.activeTimeHelp": "Active time includes only server-timed sessions by the author of a saved draft. An open, hidden, or offline tab without interaction is not counted.", "analytics.firstSaveHelp": "Time to first save is a separate server-timed elapsed interval from the first wizard interaction to draft creation. Abandoned, replaced by another tab, or offline wizards are not counted.", "analytics.shortestActiveSessions": "Three shortest active sessions", "analytics.longestActiveSessions": "Three longest active sessions", "analytics.noActiveSessions": "There are no completed active sessions in this range yet.",
    "analytics.workflowTitle": "Workflow in the selected period", "analytics.syntheticWorkflowTitle": "Synthetic workflow in the selected period", "analytics.created": "Created", "analytics.completedSyntheticDraft": "Completed synthetic draft", "analytics.sentToReview": "Sent to review", "analytics.sentToSyntheticReview": "Sent to synthetic review", "analytics.returnedToDraft": "Returned to draft", "analytics.repeatReturns": "Repeated returns", "analytics.workflowHelp": "Events are counted by lifecycle-event time. Transition reasons and texts are not shown.", "analytics.syntheticWorkflowHelp": "Events come from a deterministic synthetic lifecycle dataset, not real people’s work. Transition reasons and texts are not shown.", "analytics.currentCohort": "Current cohort state", "analytics.reportsCreatedInRange": "Reports created in range", "analytics.demoReportsInRange": "Demo reports in range", "analytics.currentQueue": "Current queue of all operational reports", "analytics.currentSyntheticQueue": "Current synthetic queue", "analytics.oldestCurrentReview": "Oldest start of the current review", "analytics.notModeled": "Not modeled", "analytics.cohortHelp": "The status belongs to reports created in the range. The review queue is a current global state, not a historical counter.", "analytics.syntheticCohortHelp": "The status belongs to synthetic reports dated in the range. Historical queue age is not modeled for the demo.", "analytics.deliveryReadiness": "Delivery readiness", "analytics.reportsWithPrivateMedia": "Reports with private media", "analytics.activePublicPassports": "Active public passports", "analytics.issuedWithoutPassport": "Issued without an active passport", "analytics.deliveryHelp": "Technical readiness of private media and the current public passport is shown; views and visitors are not tracked.", "analytics.syntheticDeliveryHelp": "The synthetic dataset does not model private storage, public URLs, QR, PDFs, or visitors.", "analytics.requiredFields": "Required fields", "analytics.optionalFields": "Optional fields", "analytics.field": "Field", "analytics.filled": "Filled", "analytics.missing": "Missing",
    "analytics.noCurrencySnapshots": "There are no official NBU rate snapshots for this range yet.", "analytics.nbu": "National Bank of Ukraine (NBU)", "analytics.sourceType": "Source type", "analytics.officialCurrencyProvider": "Official currency provider", "analytics.dataOrigin": "Data origin", "analytics.officialNbuService": "Official NBU service", "analytics.valueType": "Value type", "analytics.officialFxRate": "official FX rate", "analytics.snapshotCount": "Snapshots", "analytics.latestRate": "Latest rate", "analytics.officialRateDate": "Official rate date", "analytics.retrieved": "Retrieved", "analytics.fxHelp": "FX snapshots are immutable. They are used only for a separate USD/UAH conversion of permitted reference values and are not a stone price, valuation, or analysis.", "analytics.currencySource": "Currency source", "analytics.pair": "Pair",
    "demoDetail.created": "Created", "demoDetail.simulatedSystemEvent": "Simulated system event", "demoDetail.statusChanged": "Status changed", "demoDetail.showcaseMediaAdded": "Synthetic attachments added for demonstration preview", "demoDetail.showcaseMediaHelp": "Stone photo and plotting diagram · simulated attachments",
    "demoDetail.photoAttachment": "Stone photo · synthetic asset", "demoDetail.plottingAttachment": "Plotting diagram · synthetic asset", "demoDetail.removeFromPassport": "Remove from passport", "demoDetail.internalOnly": "DEMO · INTERNAL ONLY. A synthetic report has no public ID, URL, QR code, or anonymous endpoint.", "demoDetail.passportCode": "Passport code", "demoDetail.notCreated": "— not created", "demoDetail.qrUnavailable": "QR code is unavailable for a demo report", "demoDetail.unavailable": "Unavailable", "demoDetail.publishPassport": "Publish passport", "demoDetail.openPassport": "Open public passport", "demoDetail.copyLink": "Copy link", "demoDetail.downloadPdf": "Download demo PDF",
    "analytics.stonesHelp": "Real SOM and benchmark maps are not enabled yet: the current operational dataset has no confirmed permitted data contract or verified analysis. Below is the structure of the future surface without synthetic figures, segments, or prices.",
    "demoDetail.statusHelp": "DEMO · SYNTHETIC DATA. The report is immutable and has no public passport.", "demoDetail.referencesHelp": "Each reference belongs to a separate fictional demo provider. Values are isolated from market data and are not an expert, sale, or transaction price.",
    "demo.currencyHelp": "A separate read-only view of official NBU USD/UAH snapshots. The currency rate is not a stone reference, is not part of synthetic SOM, and is not mixed with Demo Market A/B.", "demo.expertsHelp": "Synthetic workflow for the selected period. Actors are not user accounts, and all demo reports have an issued synthetic lifecycle.", "demo.textsHelp": "Synthetic dataset metadata only: no assessment, norm, rating, or conclusion about a real expert. Text and excerpts are not shown.", "demo.qualityHelp": "Aggregated deterministic workflow facts and synthetic-field coverage only. This is not an evaluation of real people, a text-quality rating, or public tracking.", "demo.administratorsHelp": "Duration is a reproducible synthetic review interval, not a measurement of a person's actual active time.", "demo.providersHelp": "A separate read-only slice only for fictional Demo Market A/B and synthetic demo reports in the selected period.", "demo.somHelp": "Technical segmentation of the isolated synthetic dataset only. It is not a forecast, valuation, market, or investment analysis.",
    "analytics.expertsHelp": "Statuses show the current state of reports created in the selected period. Active time includes only server-recorded completed sessions for the draft author.", "analytics.textsHelp": "Metadata only: counts and length, without text, excerpts, or expert evaluation. Length is not a quality standard or rating.", "analytics.qualityHelp": "Aggregated workflow facts and field coverage only. This is not an evaluation of experts, a text-quality rating, or analytics of public-passport visitors.", "analytics.administratorsHelp": "Review duration runs from sending a report for review to the administrator decision. It does not measure a person's actual active time.", "analytics.providersHelp": "Technical facts about freshness, snapshots, attempts, and operational-draft coverage. This is not a rating, accuracy measure, or comparison of provider prices.", "analytics.currencyHelp": "Immutable official NBU USD/UAH snapshots. The filter applies to the official rate date, not the report creation time.",
    "demoDetail.statusEvent": "Draft → {status} · simulated system event", "demoDetail.systemIdc": "System IDC: Proportions {proportions}, Final Cut {cut}.",
    "demoDetail.originNatural": "Natural", "demoDetail.originLabGrown": "Laboratory-grown", "demoDetail.originOther": "Other", "demoDetail.unknown": "Not specified", "demoDetail.notAssessed": "Not assessed", "demoDetail.noneDetected": "None detected", "demoDetail.disclosed": "Disclosed", "demoDetail.confirmed": "Confirmed", "demoDetail.preliminary": "Preliminary", "demoDetail.inconclusive": "Inconclusive",
    "demo.reportActions": "Open actions for demo report {reportId}", "demo.view": "View", "demo.edit": "Edit", "demo.print": "Print", "demo.somAnalysis": "SOM analysis", "demo.readOnly": "Demo report is read-only",
    "demo.reportId": "Report ID", "demo.date": "Date", "demo.priceUsd": "Price (USD)", "demo.reportStatus": "Report status", "demo.saleStatus": "Sale status", "demo.actions": "Actions", "demo.sortBy": "Sort by {field}",
    "demo.shape": "Shape", "demo.carat": "Carat", "demo.color": "Color", "demo.clarity": "Clarity", "demo.cut": "Cut", "demo.referenceUsd": "Reference value (USD)", "demo.createdFrom": "Created from", "demo.createdTo": "Created to",
    "demo.from": "From", "demo.to": "To", "demo.applyPeriod": "Apply period", "demo.allTime": "All time",
    "demo.allReportStatuses": "All report statuses", "demo.allSaleStatuses": "All sale statuses", "demo.allExperts": "All experts",
    "demo.searchReports": "Search by demo report number", "demo.filters": "Filters", "demo.apply": "Apply", "demo.clear": "Clear",
    "analytics.completedReviews": "Completed reviews", "analytics.returned": "Returned to draft", "analytics.averageDuration": "Average duration", "analytics.medianDuration": "Median duration", "analytics.shortestReviews": "Shortest reviews", "analytics.longestReviews": "Longest reviews", "analytics.noAdministrators": "There are no administrators for this range yet.", "analytics.noCompletedReviews": "There are no completed reviews in this range yet.", "analytics.pendingReview": "Currently under review: {count}.", "analytics.noPendingReview": "There are no reports under review now.", "analytics.oldestTransferred": "Oldest transferred: {date}.",
    "analytics.expert": "Expert", "analytics.state": "State", "analytics.total": "Total", "analytics.drafts": "Drafts", "analytics.underReview": "Under review", "analytics.issued": "Issued", "analytics.void": "Voided", "analytics.activeTime": "Active time",
    "analytics.provider": "Provider", "analytics.freshness": "Freshness", "analytics.snapshots": "Snapshots", "analytics.attempts": "Attempts", "analytics.draftCoverage": "Draft coverage", "analytics.approved": "approved", "analytics.failed": "failed", "analytics.retry": "retry", "analytics.covered": "covered", "analytics.noActiveProviders": "There are no active market providers yet.", "analytics.fresh": "Fresh", "analytics.warning": "Needs attention", "analytics.stale": "Stale", "analytics.missingSnapshot": "No snapshot",
    "demoDetail.subtitle": "An isolated read-only demonstration report.", "demoDetail.back": "Back to demo reports", "demoDetail.identification": "Identification and 4C", "demoDetail.geometry": "Geometry and IDC", "demoDetail.conclusion": "Conclusion and confirmation", "demoDetail.reportState": "Report state", "demoDetail.references": "Demo reference values", "demoDetail.attachments": "Attachments", "demoDetail.passport": "Public passport", "demoDetail.history": "Change history", "demoDetail.examinationDate": "Examination / valuation date", "demoDetail.shape": "Shape", "demoDetail.carat": "Carat (ct)", "demoDetail.color": "Color", "demoDetail.clarity": "Clarity", "demoDetail.origin": "Origin", "demoDetail.treatment": "Treatment indicators", "demoDetail.identificationLevel": "Identification level", "demoDetail.identificationMethod": "Identification method", "demoDetail.identificationConclusion": "Identification conclusion", "demoDetail.expertComment": "Expert comment",
    "analytics.totalInRange": "Total in range", "analytics.nonEmptyValues": "Non-empty values", "analytics.emptyValues": "Empty values", "analytics.medianWords": "Median words", "analytics.averageWords": "Average words", "analytics.medianCharacters": "Median non-whitespace characters", "analytics.averageCharacters": "Average non-whitespace characters", "analytics.shortest": "Three shortest", "analytics.longest": "Three longest", "analytics.emptySamples": "Up to three empty values", "analytics.noValues": "There are no non-empty values in this range yet.", "analytics.emptyValue": "empty value", "analytics.sampleMetrics": "{words} words · {characters} non-whitespace characters · {date}",
    "analytics.periodRange": "Current range: from {from} to {to}", "analytics.periodFrom": "Current range: from {from}", "analytics.periodTo": "Current range: to {to}", "analytics.periodAll": "Current range: all available time.",
    "analytics.from": "From", "analytics.to": "To", "analytics.applyPeriod": "Apply period", "analytics.allTime": "All time",
    "analytics.title": "Analytics", "analytics.subtitle": "Operational workflow overview. Data is available to administrators only.", "analytics.tabs": "Analytics sections", "analytics.stones": "Stones", "analytics.experts": "Experts", "analytics.texts": "Texts", "analytics.quality": "Operations and quality", "analytics.administrators": "Administrators", "analytics.providers": "Providers", "analytics.currencySources": "Currency sources", "analytics.stonesTitle": "Stone analytics", "analytics.expertsTitle": "Experts and reports", "analytics.textsTitle": "Text fields in reports", "analytics.qualityTitle": "Operations and data completeness", "analytics.administratorsTitle": "Administrator reviews", "analytics.providersTitle": "Provider operations and coverage", "analytics.currencyTitle": "Currency sources", "analytics.expertDialogTitle": "Expert details", "analytics.providerDialogTitle": "Provider details", "analytics.close": "Close",
    "demo.previewTitle": "Featured private preview", "demo.previewDescription": "DEMO-00999 contains synthetic attachments and an internal PDF without a public ID, URL, or QR code.", "demo.openPreview": "Open DEMO-00999", "demo.currencyTitle": "Currency sources", "demo.workflowTitle": "Synthetic experts and reports", "demo.narrativesTitle": "Synthetic text fields", "demo.qualityTitle": "Synthetic operations and data completeness", "demo.administratorsTitle": "Synthetic administrator checks", "demo.providersTitle": "Synthetic providers and references", "demo.somTitle": "Segment map (SOM)", "demo.workflowDialogTitle": "Synthetic actor details", "demo.providerDialogTitle": "Source details", "demo.close": "Close",
    "demo.title": "Demo", "demo.subtitle": "An isolated synthetic dataset for an internal demonstration of the interface and technical models.", "demo.tabs": "Demo dataset sections", "demo.reports": "Demo reports", "demo.stones": "Stones", "demo.experts": "Experts", "demo.texts": "Texts", "demo.quality": "Operations and quality", "demo.administrators": "Administrators", "demo.providers": "Providers", "demo.currencySources": "Currency sources", "demo.syntheticNotice": "Isolated internal dataset: not expert, market, sale, or transaction data.",
    "market.decisionApproveDescription": "After approval, this immutable snapshot can be explicitly attached to a compatible report.", "market.decisionRejectDescription": "A rejected snapshot cannot be used as a market reference; its data remains in history.", "market.approvalComment": "Approval comment", "market.rejectionReason": "Rejection reason", "market.approveSnapshot": "Approve snapshot", "market.rejectSnapshot": "Reject snapshot", "market.fetchingNbu": "Fetching the official NBU rate…", "market.nbuSaved": "A new immutable official NBU rate snapshot was saved.", "market.fetchingOpenfacet": "Fetching OpenFacet data…", "market.candidateCreated": "Candidate created. Review coverage and approve it separately.", "market.fetchFailed": "Provider data could not be fetched.", "market.scheduleSaved": "Refresh schedule saved.", "market.scheduleSaveFailed": "Refresh schedule could not be saved.", "market.policySaved": "Provider terms saved.", "market.policySaveFailed": "Provider terms could not be saved.", "market.assignmentUpdated": "Restricted-trial assignment updated.", "market.assignmentFailed": "Assignment could not be changed.", "market.noPolicyEvents": "There are no provider-term events yet.", "market.policyEventsFailed": "Provider-term log could not be loaded.", "market.signInAgain": "Please sign in again.", "market.referenceAttached": "Market reference attached successfully.", "market.primaryMustBeEnabled": "The primary provider must be included in the enabled set.", "market.referencePolicySaved": "System reference policy saved for future drafts.", "market.referencePolicyFailed": "System reference policy could not be saved.", "market.snapshotApprovedMessage": "Snapshot approved.", "market.snapshotRejectedMessage": "Snapshot rejected.", "market.decisionSaveFailed": "Decision could not be saved.",
    "market.providersLegend": "Market-reference providers", "market.useFx": "Add a UAH equivalent using the official NBU rate", "market.saveSettings": "Save settings", "market.reportId": "Report number", "market.approvedSnapshot": "Approved snapshot", "market.applicability": "Applicability confirmation", "market.confirmAttach": "I confirm that this reference is used only for reference comparison, not as an expert or sale price.", "market.attach": "Attach market reference", "market.confirmDecision": "Confirm decision", "market.comment": "Comment", "market.optional": "Optional", "market.cancel": "Cancel", "market.confirm": "Confirm",
    "market.title": "Market data", "market.accessTerms": "Provider access and terms", "market.referencePolicy": "System reference policy", "market.automaticRefresh": "Automatic refresh", "market.providers": "Providers", "market.snapshotHistory": "Snapshot history", "market.operationLog": "Operation log", "market.attachReference": "Attach a reference to a report",
    "market.noActiveProviders": "There are no active market-reference providers.", "market.primaryForDashboard": "Primary for the report list", "market.accessMode": "Access mode", "market.disabled": "Disabled", "market.restrictedTrial": "Restricted trial", "market.standardInternal": "Standard internal", "market.dailyRequestLimit": "Daily request limit", "market.trialUntil": "Trial active until (UTC)", "market.termsReference": "Terms link or short note", "market.accessPolicyNote": "Only natural stones and internal use are allowed; public display and ML are disabled in this release.", "market.assignedTrialAdministrators": "Assigned restricted-trial administrators:", "market.assignmentsTrialOnly": "Assignments are available only for restricted trial.", "market.showPolicyLog": "Show policy log", "market.saveTerms": "Save terms", "market.noSchedules": "Schedules have not been created yet. Apply migration 0013_market_provider_operations.", "market.enableScheduledRefresh": "Enable scheduled refresh", "market.scheduleTime": "Time (Europe/Kyiv)", "market.warnAfterHours": "Warn after, hours", "market.blockAfterHours": "Block after, hours", "market.saveSchedule": "Save schedule", "market.invalidSchedule": "Check the time and thresholds: blocking cannot be earlier than warning.",
    "app.title": "Diamant ID",
    "brand.home": "Diamant ID home",
    "navigation.primary": "Primary navigation",
    "navigation.verifyPassport": "Verify passport",
    "navigation.signIn": "Sign in",
    "navigation.allReports": "All reports",
    "navigation.demo": "Demo",
    "navigation.experts": "Experts",
    "navigation.references": "References",
    "navigation.marketData": "Market data",
    "navigation.analytics": "Analytics",
    "navigation.profile": "Profile",
    "navigation.newReport": "New report",
    "auth.administrator": "Administrator",
    "auth.gemologist": "Gemologist",
    "auth.user": "User",
    "auth.signOut": "Sign out",
    "menu.open": "Open menu",
    "session.saved": "Your session is preserved. The API is temporarily unavailable.",
    "session.retry": "Try again",
    "footer.privacy": "Privacy policy",
    "footer.documentation": "Documentation",
    "locale.switcher": "Language",
    "locale.en": "English",
    "locale.uk": "Ukrainian",
    "landing.title": "Diamond identification and assessment",
    "landing.subtitle": "Reliable passport verification and expert diamond reports in one workspace.",
    "landing.verifyPassport": "Verify passport",
    "landing.signIn": "Sign in to work with reports",
    "landing.heroAlt": "Diamond held in gemological tweezers",
    "landing.passportTitle": "Verification you can trust",
    "landing.passportDescription": "A public passport opens from a direct link, a QR-code link, or a code on the report page. Enter only the code here; an internal report number is not used for this.",
    "landing.passportCode": "Public passport code",
    "landing.passportPlaceholder": "Enter the code from the report page",
    "landing.verify": "Verify",
    "landing.principles": "Diamant ID capabilities",
    "landing.expertReports": "Expert reports",
    "landing.expertReportsText": "Consistent recording of stone characteristics and assessment results.",
    "landing.dataControl": "Data control",
    "landing.dataControlText": "A clear distinction between an expert conclusion and a calculated system result.",
    "landing.passportVerification": "Passport verification",
    "landing.passportVerificationText": "A dedicated public route for issued reports after passport and QR issuance.",
    "login.title": "Sign in",
    "login.subtitle": "Please authenticate to continue",
    "login.username": "Username",
    "login.password": "Password",
    "login.submit": "Sign in",
    "login.error": "Sign-in failed: {message}",
    "passport.invalidInternalNumber": "An internal report number is not a public passport code.",
    "passport.invalidCode": "Enter the public passport code shown on the report page.",
    "wizard.notSpecified": "Not specified",
    "wizard.requiredStep": "Complete the required fields in step {step}.",
    "wizard.referencesFailed": "Reference data could not be loaded: {message}",
    "wizard.noFile": "No file selected",
    "wizard.noMarketReference": "No system reference is available for the entered characteristics.",
    "wizard.referenceSnapshot": "{provider} · snapshot #{snapshot}. The value will be recorded when the draft is saved.",
    "wizard.snapshotValue": "{currency} {amount} · snapshot #{snapshot}",
    "wizard.startedNew": "A new unsaved entry has started.",
    "wizard.restored": "Unsaved entry restored. Add attachments again.",
    "wizard.leaveNavigation": "The entered data has not become a server draft. It remains only in this tab and can be explicitly restored after you return.",
    "wizard.leaveLogout": "The entered data has not become a server draft. After signing out it remains only in this tab and can be explicitly restored only after you sign in again with this account.",
    "wizard.signOut": "Sign out",
    "wizard.go": "Go",
    "wizard.saving": "Saving draft…",
    "wizard.saveFailed": "Draft could not be saved: {message}",
    "wizard.pageTitle": "New report",
    "wizard.pageSubtitle": "Create an expert stone-report draft.",
    "wizard.steps": "Report creation steps",
    "wizard.step1Short": "1. Basics",
    "wizard.step1": "1. Identification and 4C",
    "wizard.step2Short": "2. Geometry",
    "wizard.step2": "2. Geometry (IDC)",
    "wizard.step3Short": "3. Conclusion",
    "wizard.step3": "3. Conclusion and media",
    "wizard.identification": "Identification",
    "wizard.nextReportId": "Next report number",
    "wizard.idServerAssigned": "The server assigns the final number when saving.",
    "wizard.examinationDate": "Examination / assessment date",
    "wizard.shape": "Shape",
    "wizard.origin": "Origin",
    "wizard.fourCs": "4C characteristics",
    "wizard.caratWeight": "Carat weight",
    "wizard.color": "Color",
    "wizard.clarity": "Clarity",
    "wizard.loadingReference": "Loading reference data…",
    "wizard.dimensions": "Dimensions",
    "wizard.length": "Length (mm)", "wizard.width": "Width (mm)", "wizard.depth": "Depth (mm)",
    "wizard.cuttingParameters": "Cutting parameters (IDC)", "wizard.table": "Table (%)", "wizard.totalDepth": "Total depth (%)",
    "wizard.crownAngle": "Crown angle (°)", "wizard.pavilionAngle": "Pavilion angle (°)", "wizard.girdle": "Girdle thickness", "wizard.culet": "Culet size",
    "wizard.finish": "Finish", "wizard.polish": "Polish", "wizard.symmetry": "Symmetry", "wizard.fluorescence": "Fluorescence",
    "wizard.expertConclusion": "Expert conclusion", "wizard.treatment": "Treatment indication", "wizard.identificationStatus": "Identification confidence",
    "wizard.identificationMethod": "Identification method", "wizard.identificationConclusion": "Identification conclusion", "wizard.expertComment": "Expert comment",
    "wizard.media": "Media", "wizard.plotting": "Plotting diagram", "wizard.stonePhoto": "Stone photo", "wizard.chooseFile": "Choose file",
    "wizard.privateMediaHelp": "JPEG, PNG or WebP, up to 10 MB. Stored privately.", "wizard.back": "Back", "wizard.clearEntry": "Clear entry", "wizard.saveDraft": "Save draft", "wizard.next": "Next",
    "wizard.restoreTitle": "Restore unsaved entry?", "wizard.restoreDescription": "Unsaved data for this tab was found. It was not sent to the server.", "wizard.restoreMedia": "Attachments are not restored — add files again after restoring.", "wizard.startNew": "Start over", "wizard.restore": "Restore",
    "wizard.clearTitle": "Clear unsaved entry?", "wizard.close": "Close", "wizard.clearDescription": "This tab's data will be removed from the form and local storage. No saved report will change.", "wizard.cancel": "Cancel", "wizard.stay": "Stay", "wizard.leaveTitle": "Leave wizard?",
    "detail.privateReport": "Private report", "detail.loadingReport": "Loading report…", "detail.subtitle": "Data, expert conclusion, attachments, and change history.", "detail.backToReports": "Back to all reports", "detail.editDraft": "Edit draft", "detail.saveChanges": "Save changes", "detail.reportState": "Report state", "detail.transitionReason": "Status-change comment", "detail.transitionReasonPlaceholder": "Optional, but recommended when returning or voiding", "detail.narrativeQuality": "Text-field check", "detail.narrativeHelp": "Automated completion signals do not assess the professional conclusion and do not block saving.", "detail.loading": "Loading…", "detail.marketReference": "Market reference value", "detail.marketReferenceHelp": "A market reference is not an expert, sale, or transaction price.", "detail.attachments": "Attachments", "detail.history": "Change history",
    "detail.stonePhoto": "Stone photo", "detail.plottingDiagram": "Cutting diagram (plotting)", "detail.eventCreated": "Created", "detail.eventUpdated": "Draft data updated", "detail.eventStatusChanged": "Status changed", "detail.eventPassportPublished": "Public passport published", "detail.eventPassportReissued": "Public passport reissued", "detail.eventPassportRevoked": "Public passport revoked", "detail.eventMediaPublished": "Attachment published in passport", "detail.eventMediaUnpublished": "Attachment removed from passport", "detail.eventSystemReference": "System reference value added", "detail.eventAdminReference": "Reference value confirmed by administrator", "detail.eventLegacyImport": "Imported from the previous database", "detail.notConfirmed": "Not confirmed", "detail.chooseColor": "Choose a color", "detail.chooseClarity": "Choose a clarity", "detail.chooseValue": "Choose a value", "detail.chooseGrade": "Choose a grade", "detail.notSpecified": "Not specified", "detail.noEvents": "No events yet.",
    "detail.publicPassport": "Public passport", "detail.passportIssuedOnly": "Available only for an issued report.", "detail.passportCode": "Passport code", "detail.openPublicPassport": "Open public passport", "detail.passportQrAlt": "Public passport QR code", "detail.publishPassport": "Publish passport", "detail.copyLink": "Copy link", "detail.copyCode": "Copy code", "detail.downloadPdf": "Download PDF", "detail.reissueLink": "Reissue link", "detail.revokePublication": "Revoke publication", "detail.confirmAttachmentPublication": "Confirm attachment publication", "detail.confirm": "Confirm", "detail.attachment": "Attachment", "detail.removeFromPassport": "Remove from passport", "detail.publishInPassport": "Publish in passport", "detail.publishedInPassport": "Published in passport", "detail.publishing": "Publishing…", "detail.publishingPassport": "Publishing passport…", "detail.passportPublished": "Passport published.", "detail.publishPassportFailed": "Passport could not be published.", "detail.passportNotPublished": "Passport has not been published yet.", "detail.publicLinkCopied": "Public link copied.", "detail.copyLinkFailed": "Link could not be copied.", "detail.passportCodeCopied": "Public passport code copied.", "detail.copyCodeFailed": "Code could not be copied.", "detail.generatingPassportPdf": "Generating passport PDF…", "detail.passportPdfDownloaded": "Passport PDF downloaded.", "detail.passportPdfFailed": "Passport PDF could not be generated.", "detail.reissueConfirm": "Reissue the passport? The previous code, link, and QR will stop working.", "detail.reissuingPassport": "Reissuing passport…", "detail.passportReissued": "A new code, link, and QR code were created.", "detail.reissueFailed": "Link could not be reissued.", "detail.revokeConfirm": "Revoke the public passport? The code, link, and QR will stop working immediately.", "detail.revokingPassport": "Revoking publication…", "detail.passportRevoked": "Passport publication revoked.", "detail.revokeFailed": "Passport could not be revoked.", "detail.sendForReview": "Send for review", "detail.returnToDraft": "Return to draft", "detail.issueReport": "Issue report", "detail.voidReport": "Void report", "detail.issueNeedsProportions": "An expert Proportions grade is required to issue the report.", "detail.reviewNeedsProportions": "To issue the report, return it to draft and choose an expert Proportions grade.", "detail.draftEditHelp": "The author or an administrator can edit the draft.", "detail.lockedAfterReview": "After sending for review, report fields are locked; the server controls transitions.",
    "detail.noNarrativeWarnings": "There are no explanatory completion signals right now.", "detail.noPrivateAttachments": "There are no private attachments.", "detail.noMarketReferences": "There is no system or administrator-confirmed market reference yet.", "detail.marketReferenceDescription": "Each reference belongs to a separate provider and snapshot. The system reference is created automatically from the latest approved snapshot; an administrator separately verifies the confirmed reference. Reference values are not expert, sale, or transaction prices.", "detail.previousReferencesCollapsed": "The current record is open; earlier saved references are collapsed.", "detail.confirmation": "Confirmation", "detail.systemReferenceNote": "Calculated automatically from the latest approved {provider} snapshot; applicability has not been confirmed by an administrator.", "detail.copyFailed": "Data could not be copied", "detail.passportPublishedDescription": "The passport is published. It can be checked by link, QR, or code; reissuing immediately revokes the prior access data.", "detail.passportStateLoadFailed": "Publication state could not be loaded.", "detail.reportIdMissing": "No report number was provided.", "detail.publishAttachmentDescription": "The image will be available in the public passport only through an active link or QR code. It is not included in the PDF.", "detail.unpublishAttachmentDescription": "The image will no longer appear in the public passport. The private report attachment remains saved.", "detail.createdAt": "Created: {date}", "detail.systemSummary": "System IDC: Proportions {proportions}, Final Cut {cut}.", "detail.expertSummary": "Expert grades: Proportions {proportions}, final Cut {cut}.", "detail.narrativeUnavailable": "Text metadata is temporarily unavailable.", "detail.marketReferencesLoadFailed": "Market reference value could not be loaded.", "detail.statusChanging": "Changing status…", "detail.statusUpdated": "Report status updated.", "detail.statusUpdateFailed": "Report status could not be changed.", "detail.reportForbidden": "You do not have access to this report.", "detail.reportLoadFailed": "Private report could not be loaded.", "detail.pagePreparationFailed": "The report page could not be prepared. Your session is saved — refresh after the API is restored.", "detail.attachmentPublished": "Attachment published in passport.", "detail.attachmentUnpublished": "Attachment removed from passport.", "detail.attachmentVisibilityFailed": "Attachment visibility could not be changed.", "detail.savingChanges": "Saving changes…", "detail.changesSaved": "Draft changes saved.", "detail.saveChangesFailed": "Changes could not be saved.",
    "dashboard.statusDraft": "Draft", "dashboard.statusReview": "In review", "dashboard.statusIssued": "Issued", "dashboard.statusVoid": "Voided", "dashboard.notSold": "Not sold", "dashboard.sold": "Sold",
    "dashboard.view": "View", "dashboard.edit": "Edit", "dashboard.editDraftOnly": "Editing is available only for a draft", "dashboard.print": "Print", "dashboard.loading": "Loading reports…", "dashboard.empty": "No reports match the current conditions.", "dashboard.loadFailed": "Reports could not be loaded. Refresh the page or try again later.",
    "dashboard.title": "All reports", "dashboard.subtitle": "Manage certificates and assessments.", "dashboard.newReport": "New report", "dashboard.search": "Search by report number", "dashboard.filters": "Filters", "dashboard.allReportStatuses": "All report statuses", "dashboard.allSaleStatuses": "All sale statuses", "dashboard.allExperts": "All experts",
    "dashboard.reportStatus": "Report status", "dashboard.saleStatus": "Sale status", "dashboard.expert": "Expert", "dashboard.shape": "Shape", "dashboard.any": "Any", "dashboard.carat": "Carat", "dashboard.from": "From", "dashboard.to": "To", "dashboard.color": "Color", "dashboard.clarity": "Clarity", "dashboard.cut": "Cut", "dashboard.referenceUsd": "Reference value (USD)", "dashboard.createdFrom": "Created from", "dashboard.createdTo": "Created to", "dashboard.apply": "Apply", "dashboard.clear": "Clear", "dashboard.referenceNote": "Reference values (USD) are generated for new or changed drafts by the configured provider (currently OpenFacet). SYS means a system reference value and ADM means an administrator-confirmed applicable reference; the source is always shown. This is not an expert, sale, or transaction price. A UAH equivalent is added only when the NBU exchange rate is enabled and is fixed at creation.",
    "dashboard.reportId": "Report ID", "dashboard.date": "Date", "dashboard.caratColumn": "Carat (ct)", "dashboard.priceUsd": "Value (USD)", "dashboard.actions": "Actions", "dashboard.pagination": "Report pagination", "dashboard.sortReportId": "Sort by report ID", "dashboard.sortDate": "Sort by date", "dashboard.sortShape": "Sort by shape", "dashboard.sortCarat": "Sort by carat", "dashboard.sortColor": "Sort by color", "dashboard.sortClarity": "Sort by clarity", "dashboard.sortCut": "Sort by cut", "dashboard.sortPrice": "Sort by reference value", "dashboard.sortReportStatus": "Sort by report status", "dashboard.sortSaleStatus": "Sort by sale status",
    "dashboard.openActions": "Open actions for report {reportId}", "dashboard.referenceTypeDemo": "Demo reference value", "dashboard.referenceTypeSystem": "System reference value", "dashboard.referenceTypeAdmin": "Administrator-confirmed reference value", "dashboard.referenceExplanation": "Reference value explanation for report {reportId}", "dashboard.referenceType": "Type", "dashboard.provider": "Provider", "dashboard.providerSnapshot": "Provider snapshot", "dashboard.observed": "Observed", "dashboard.equivalent": "Equivalent", "dashboard.nbuRate": "NBU rate", "dashboard.notAvailableForDemo": "Not available for synthetic demo", "dashboard.notCalculatedForDemo": "Not calculated for synthetic demo", "dashboard.notApplicableForDemo": "Not applicable for synthetic demo", "dashboard.nbuRateValue": "{rate} UAH/USD · {date} · snapshot #{snapshot}", "dashboard.otherReferences": "Other available reference values:", "dashboard.demoReferenceWarning": "Synthetic demo value; it is not a market, expert, sale, or transaction price.", "dashboard.systemReferenceWarning": "Calculated by the system from the latest approved snapshot; it is not an expert, sale, or transaction price.", "dashboard.adminReferenceWarning": "Applicability was confirmed by an administrator; it is not an expert, sale, or transaction price.", "dashboard.openPrivateReport": "Open private report view", "dashboard.firstPage": "First page", "dashboard.previousPage": "Previous page", "dashboard.nextPage": "Next page", "dashboard.lastPage": "Last page",
    "profile.title": "Profile", "profile.subtitle": "Manage your personal details and password.", "profile.details": "Profile details", "profile.username": "Username", "profile.role": "Role", "profile.firstName": "First name", "profile.lastName": "Last name", "profile.middleName": "Middle name", "profile.saveDetails": "Save details", "profile.changePassword": "Change password", "profile.currentPassword": "Current password", "profile.newPassword": "New password", "profile.confirmPassword": "Confirm new password", "profile.submitPassword": "Change password", "profile.demoAccess": "Demo access", "profile.demoAccessHelp": "An isolated synthetic dataset for internal demonstration. It contains no real reports, market data, or public passports.", "profile.enableDemoAccess": "Enable Demo access for my account", "profile.saveAccess": "Save access", "profile.partnerControls": "Partner-data management access", "profile.partnerControlsHelp": "This mode opens only internal tools for managing provider terms. It does not enable an external provider, issue keys, or grant trial access.", "profile.enablePartnerControls": "Enable partner-data management access for my account", "profile.saved": "Profile details saved.", "profile.demoEnabled": "Demo access enabled.", "profile.demoDisabled": "Demo access disabled.", "profile.partnerEnabled": "Partner-data management access enabled.", "profile.partnerDisabled": "Partner-data management access disabled.", "profile.passwordMismatch": "The new password and confirmation do not match.", "profile.passwordChanged": "Password changed.",
    "experts.deactivate": "Deactivate", "experts.activate": "Activate", "experts.adminOnly": "This page is available only to administrators.", "experts.username": "Username", "experts.name": "Name", "experts.role": "Role", "experts.active": "Active", "experts.inactive": "Inactive", "experts.state": "State", "experts.actions": "Actions", "experts.edit": "Edit", "experts.created": "Expert created.", "experts.updated": "Account updated.", "experts.stateUpdated": "Account state updated.",
    "experts.title": "Experts", "experts.subtitle": "Create accounts, change roles, and safely deactivate access.", "experts.new": "New expert", "experts.temporaryPassword": "Temporary password", "experts.create": "Create expert", "experts.accounts": "Accounts", "experts.accountsHelp": "Deactivation does not remove reports, passports, or change history. You cannot deactivate your own account.", "experts.search": "Search accounts", "experts.searchPlaceholder": "Search by username or name", "experts.pagination": "Account pagination", "experts.editAccount": "Edit account", "experts.close": "Close", "experts.newTemporaryPassword": "New temporary password", "experts.passwordHelp": "Leave empty if the password does not need to change.", "experts.save": "Save changes",
    "references.title": "References", "references.subtitle": "Current values provided by the server to report forms.", "references.help": "Editing with a reason, source document, and versions for new reports is planned separately in task 105. Current data is view-only.", "references.shape": "Shape", "references.origin": "Origin", "references.treatment": "Treatment indication", "references.identificationStatus": "Identification confidence", "references.marketStatus": "Market status", "references.reportStatus": "Report status", "references.girdle": "Girdle thickness", "references.culet": "Culet size", "references.code": "Code", "references.value": "Value",
    "market.snapshotCandidate": "Candidate", "market.snapshotApproved": "Approved", "market.snapshotRejected": "Rejected", "market.fresh": "Current", "market.warning": "Needs refresh", "market.stale": "Stale", "market.missing": "No snapshots", "market.operationSuccess": "Successful", "market.operationNoChange": "No change", "market.operationFailed": "Failed", "market.operationSkipped": "Skipped", "market.dataState": "Data state", "market.lastRetrieved": "last retrieved", "market.documentation": "Documentation", "market.terms": "Terms of use", "market.refreshNow": "Refresh now", "market.fetchCandidate": "Fetch candidate", "market.noSnapshots": "No snapshots yet.", "market.sourceMethodology": "Source methodology", "market.decision": "Decision", "market.approve": "Approve", "market.reject": "Reject", "market.manual": "Manual", "market.scheduled": "Scheduled", "market.attempt": "attempt", "market.noOperations": "No operations yet.", "market.selectSnapshot": "Select a snapshot", "market.noApprovedSnapshots": "No approved snapshots",
    "narrative.fields": "Text fields", "narrative.identificationMethod": "Identification method", "narrative.identificationConclusion": "Identification conclusion", "narrative.expertComment": "Expert comment", "narrative.statusTransition": "Status-change event without a comment", "narrative.show": "Show:", "narrative.showFields": "Show text fields", "narrative.empty": "Empty", "narrative.filled": "Filled", "narrative.demoNote": "Synthetic lifecycle has no text comments, so this option is not modeled.", "narrative.realNote": "The status-change event is checked in the selected date range.",
  },
  uk: {
    "analytics.durationHours": "{hours} год {minutes} хв", "analytics.durationMinutes": "{minutes} хв {seconds} с", "analytics.durationSeconds": "{seconds} с", "analytics.notSpecified": "Не вказано", "analytics.invalidPeriod": "Дата «Від» не може бути пізнішою за дату «До».", "analytics.narrativesUnavailable": "Текстові метадані тимчасово недоступні.", "analytics.qualityUnavailable": "Операційні метадані тимчасово недоступні.", "analytics.providersUnavailable": "Метадані постачальників тимчасово недоступні.", "analytics.currencyUnavailable": "Метадані валютних джерел тимчасово недоступні.", "analytics.adminOnly": "Аналітика доступна лише адміністратору.", "analytics.loadFailed": "Не вдалося завантажити аналітику. Спробуйте оновити сторінку пізніше.",
    "analytics.freshnessState": "Стан актуальності", "analytics.latestApprovedSnapshot": "Останній затверджений знімок", "analytics.candidates": "Кандидати", "analytics.approvedCount": "Затверджено", "analytics.rejectedCount": "Відхилено", "analytics.totalAttempts": "Усього спроб", "analytics.scheduled": "За графіком", "analytics.manual": "Вручну", "analytics.retries": "Повторні спроби", "analytics.failedAttempts": "Невдалі спроби", "analytics.draftsInRange": "Чернеток у зрізі", "analytics.coveredByReference": "Покрито орієнтиром", "analytics.excludedByOrigin": "Виключено за походженням", "analytics.missingCharacteristics": "Бракує характеристик", "analytics.noCurrentSnapshot": "Немає актуального знімка", "analytics.quoteNotCovered": "Немає відповідного орієнтира", "analytics.noValue": "Немає", "analytics.providerAccess": "Доступ і умови постачальника", "analytics.accessMode": "Режим", "analytics.disabled": "Вимкнено", "analytics.restrictedTrial": "Обмежений пробний доступ", "analytics.standardInternal": "Внутрішній стандартний", "analytics.notConfigured": "Не налаштовано", "analytics.trialUntil": "Пробний доступ діє до", "analytics.notApplicable": "Не застосовується", "analytics.dailyLimit": "Денний ліміт", "analytics.assignedAdministrators": "Призначено адміністраторів", "analytics.lastPolicyChange": "Остання зміна умов", "analytics.noPolicyEvents": "Подій ще немає", "analytics.policyReadOnlyHelp": "Це інформаційний факт конфігурації. Керувати умовами можна лише в «Ринкових даних» адміністратору з увімкненим відповідним доступом у профілі.", "analytics.coveredReports": "Приклади покритих звітів: ",
    "analytics.accountState": "Стан облікового запису", "analytics.active": "Активний", "analytics.inactive": "Неактивний", "analytics.completedSessions": "Завершені робочі сесії", "analytics.averageActiveSession": "Середня активна сесія", "analytics.medianActiveSession": "Медіанна активна сесія", "analytics.firstSaveMeasurements": "Збережень із виміром підготовки", "analytics.timeToFirstSave": "Час до першого збереження", "analytics.averageTimeToFirstSave": "Середній час до першого збереження", "analytics.medianTimeToFirstSave": "Медіанний час до першого збереження", "analytics.activeTimeHelp": "Активний час охоплює лише зафіксовані сервером сесії автора збереженої чернетки. Відкрита, прихована або автономна вкладка без взаємодії не зараховується.", "analytics.firstSaveHelp": "Час до першого збереження — окремий виміряний сервером інтервал від першої взаємодії з майстром до створення чернетки. Покинуті, замінені іншою вкладкою або автономні майстри не враховуються.", "analytics.shortestActiveSessions": "Три найкоротші активні сесії", "analytics.longestActiveSessions": "Три найдовші активні сесії", "analytics.noActiveSessions": "Завершених активних сесій у цьому періоді поки немає.",
    "analytics.workflowTitle": "Робочий процес у вибраному періоді", "analytics.syntheticWorkflowTitle": "Синтетичний робочий процес у вибраному періоді", "analytics.created": "Створено", "analytics.completedSyntheticDraft": "Завершено синтетичну чернетку", "analytics.sentToReview": "Передано на перевірку", "analytics.sentToSyntheticReview": "Передано на синтетичну перевірку", "analytics.returnedToDraft": "Повернено у чернетку", "analytics.repeatReturns": "Повторні повернення", "analytics.workflowHelp": "Події рахуються за часом зміни життєвого циклу. Причини переходів і тексти не показуються.", "analytics.syntheticWorkflowHelp": "Події походять із детермінованого синтетичного набору життєвого циклу, а не з роботи реальних людей. Причини переходів і тексти не показуються.", "analytics.currentCohort": "Поточний стан когорти", "analytics.reportsCreatedInRange": "Звітів створено у зрізі", "analytics.demoReportsInRange": "Демо-звітів у зрізі", "analytics.currentQueue": "Поточна черга всіх робочих звітів", "analytics.currentSyntheticQueue": "Поточна синтетична черга", "analytics.oldestCurrentReview": "Найдавніший початок поточної перевірки", "analytics.notModeled": "Не моделюється", "analytics.cohortHelp": "Статус належить звітам, створеним у зрізі. Черга перевірки — поточний глобальний стан, а не історичний лічильник.", "analytics.syntheticCohortHelp": "Статус належить синтетичним звітам, датованим у зрізі. Історичний вік черги для демо не моделюється.", "analytics.deliveryReadiness": "Готовність до видачі", "analytics.reportsWithPrivateMedia": "Звіти з приватними вкладеннями", "analytics.activePublicPassports": "Активні публічні паспорти", "analytics.issuedWithoutPassport": "Видані без активного паспорта", "analytics.deliveryHelp": "Показано технічну готовність приватних вкладень та поточного публічного паспорта; перегляди або відвідувачі не відстежуються.", "analytics.syntheticDeliveryHelp": "Синтетичний набір не моделює приватне сховище, публічні URL, QR, PDF чи відвідувачів.", "analytics.requiredFields": "Обов’язкові поля", "analytics.optionalFields": "Додаткові поля", "analytics.field": "Поле", "analytics.filled": "Заповнено", "analytics.missing": "Немає",
    "analytics.noCurrencySnapshots": "Знімків офіційного курсу НБУ за цим зрізом поки немає.", "analytics.nbu": "Національний банк України (НБУ)", "analytics.sourceType": "Тип джерела", "analytics.officialCurrencyProvider": "Офіційний валютний провайдер", "analytics.dataOrigin": "Походження даних", "analytics.officialNbuService": "Офіційний сервіс НБУ", "analytics.valueType": "Тип значень", "analytics.officialFxRate": "офіційний FX-курс", "analytics.snapshotCount": "Кількість знімків", "analytics.latestRate": "Останній курс", "analytics.officialRateDate": "Офіційна дата курсу", "analytics.retrieved": "Останнє отримання", "analytics.fxHelp": "FX-знімки зберігаються immutable. Вони застосовуються лише для окремої USD/UAH-конвертації дозволених орієнтирів і не є ціною, оцінкою або аналітикою каменю.", "analytics.currencySource": "Валютне джерело", "analytics.pair": "Пара",
    "demoDetail.created": "Створено", "demoDetail.simulatedSystemEvent": "Змодельована системна подія", "demoDetail.statusChanged": "Статус змінено", "demoDetail.showcaseMediaAdded": "Синтетичні вкладення додано до демонстраційного перегляду", "demoDetail.showcaseMediaHelp": "Фото каменю та схема огранювання · змодельовані вкладення",
    "demoDetail.photoAttachment": "Фото каменю · синтетичний матеріал", "demoDetail.plottingAttachment": "Схема огранювання · синтетичний матеріал", "demoDetail.removeFromPassport": "Прибрати з паспорта", "demoDetail.internalOnly": "ДЕМО · ЛИШЕ ДЛЯ ВНУТРІШНЬОГО ВИКОРИСТАННЯ. Для синтетичного звіту не створюються публічний ID, URL, QR-код або анонімний маршрут.", "demoDetail.passportCode": "Код паспорта", "demoDetail.notCreated": "— не створюється", "demoDetail.qrUnavailable": "QR-код недоступний для демо-звіту", "demoDetail.unavailable": "Недоступний", "demoDetail.publishPassport": "Опублікувати паспорт", "demoDetail.openPassport": "Відкрити публічний паспорт", "demoDetail.copyLink": "Скопіювати посилання", "demoDetail.downloadPdf": "Завантажити демо-PDF",
    "analytics.stonesHelp": "Реальна SOM і карта порівняння ще не запускаються: у поточному робочому наборі немає підтвердженого дозволеного контракту даних і верифікованого аналізу. Нижче — структура майбутнього розділу без синтетичних чисел, сегментів чи цін.",
    "demoDetail.statusHelp": "ДЕМО · СИНТЕТИЧНІ ДАНІ. Звіт незмінний і не має публічного паспорта.", "demoDetail.referencesHelp": "Кожен орієнтир належить окремому вигаданому демо-постачальнику. Значення ізольовані від ринкових даних і не є експертною, продажною чи транзакційною ціною.",
    "demo.currencyHelp": "Окремий огляд лише для читання офіційних знімків USD/UAH НБУ. Валютний курс не є орієнтиром каменю, не входить до синтетичного SOM і не змішується з Демо-ринком A/B.", "demo.expertsHelp": "Показано синтетичний робочий процес за вибраний період. Учасники не є обліковими записами, а всі демо-звіти мають виданий синтетичний життєвий цикл.", "demo.textsHelp": "Лише метадані синтетичного демо-набору: без оцінювання, норми, рейтингу чи висновку про реального експерта. Самі тексти й уривки не показуються.", "demo.qualityHelp": "Лише агреговані детерміновані факти робочого процесу й покриття синтетичних полів. Це не оцінка реальних людей, не рейтинг якості текстів і не відстеження відвідувачів.", "demo.administratorsHelp": "Тривалість — відтворюваний синтетичний інтервал перевірки, а не вимір фактичного активного часу людини.", "demo.providersHelp": "Окремий зріз лише для вигаданих Демо-ринків A/B і синтетичних демо-звітів у вибраному періоді.", "demo.somHelp": "Технічна сегментація лише ізольованого синтетичного набору. Це не прогноз, не оцінка, не ринкова чи інвестиційна аналітика.",
    "analytics.expertsHelp": "Статуси показують поточний стан звітів, створених у вибраному періоді. Активний час — лише серверно зафіксовані завершені сесії автора чернетки.", "analytics.textsHelp": "Лише метадані: лічильники та довжина, без текстів, фрагментів або оцінки експерта. Довжина не є нормою якості чи рейтингом.", "analytics.qualityHelp": "Лише агреговані факти робочого процесу й покриття полів. Це не оцінка експертів, не рейтинг якості текстів і не аналітика відвідувачів публічних паспортів.", "analytics.administratorsHelp": "Тривалість етапу перевірки: від передачі звіту на перевірку до рішення адміністратора. Це не вимір фактичного активного часу людини.", "analytics.providersHelp": "Це технічні відомості про актуальність, знімки, спроби та покриття робочих чернеток. Це не рейтинг, точність чи порівняння цін постачальників.", "analytics.currencyHelp": "Незмінні офіційні знімки USD/UAH НБУ. Фільтр застосовується до офіційної дати курсу, не до часу створення звіту.",
    "demoDetail.statusEvent": "Чернетка → {status} · змодельована системна подія", "demoDetail.systemIdc": "Системний IDC: Proportions {proportions}, Final Cut {cut}.",
    "demoDetail.originNatural": "Природний", "demoDetail.originLabGrown": "Лабораторно вирощений", "demoDetail.originOther": "Інше", "demoDetail.unknown": "Не визначено", "demoDetail.notAssessed": "Не оцінено", "demoDetail.noneDetected": "Не виявлено", "demoDetail.disclosed": "Заявлено", "demoDetail.confirmed": "Підтверджено", "demoDetail.preliminary": "Попередній", "demoDetail.inconclusive": "Невизначено",
    "demo.reportActions": "Відкрити дії для демо-звіту {reportId}", "demo.view": "Переглянути", "demo.edit": "Редагувати", "demo.print": "Друк", "demo.somAnalysis": "Аналіз SOM", "demo.readOnly": "Демо-звіт доступний лише для читання",
    "demo.reportId": "ID звіту", "demo.date": "Дата", "demo.priceUsd": "Ціна (USD)", "demo.reportStatus": "Статус звіту", "demo.saleStatus": "Статус продажу", "demo.actions": "Дії", "demo.sortBy": "Сортувати за {field}",
    "demo.shape": "Форма (Shape)", "demo.carat": "Вага (Carat)", "demo.color": "Колір (Color)", "demo.clarity": "Чистота (Clarity)", "demo.cut": "Якість (Cut)", "demo.referenceUsd": "Довідковий орієнтир (USD)", "demo.createdFrom": "Дата створення: від", "demo.createdTo": "Дата створення: до",
    "demo.from": "Від", "demo.to": "До", "demo.applyPeriod": "Застосувати період", "demo.allTime": "За весь час",
    "demo.allReportStatuses": "Усі статуси звіту", "demo.allSaleStatuses": "Усі статуси продажу", "demo.allExperts": "Усі експерти",
    "demo.searchReports": "Пошук за номером демо-звіту", "demo.filters": "Фільтри", "demo.apply": "Застосувати", "demo.clear": "Очистити",
    "analytics.completedReviews": "Завершено перевірок", "analytics.returned": "Повернуто до чернетки", "analytics.averageDuration": "Середня тривалість", "analytics.medianDuration": "Медіанна тривалість", "analytics.shortestReviews": "Найкоротші перевірки", "analytics.longestReviews": "Найдовші перевірки", "analytics.noAdministrators": "Адміністраторів для цього зрізу поки немає.", "analytics.noCompletedReviews": "Завершених перевірок у цьому зрізі поки немає.", "analytics.pendingReview": "Зараз на перевірці: {count}.", "analytics.noPendingReview": "Зараз немає звітів на перевірці.", "analytics.oldestTransferred": "Найдавніше передано: {date}.",
    "analytics.expert": "Експерт", "analytics.state": "Стан", "analytics.total": "Усього", "analytics.drafts": "Чернетки", "analytics.underReview": "На перевірці", "analytics.issued": "Видано", "analytics.void": "Анульовано", "analytics.activeTime": "Активний час",
    "analytics.provider": "Провайдер", "analytics.freshness": "Актуальність", "analytics.snapshots": "Знімки", "analytics.attempts": "Спроби", "analytics.draftCoverage": "Покриття чернеток", "analytics.approved": "затверджено", "analytics.failed": "невдало", "analytics.retry": "повтор", "analytics.covered": "покрито", "analytics.noActiveProviders": "Активних ринкових провайдерів поки немає.", "analytics.fresh": "Актуальний", "analytics.warning": "Потребує уваги", "analytics.stale": "Застарілий", "analytics.missingSnapshot": "Немає знімка",
    "demoDetail.subtitle": "Ізольований демонстраційний звіт лише для читання.", "demoDetail.back": "До демо-звітів", "demoDetail.identification": "Ідентифікація та 4C", "demoDetail.geometry": "Геометрія та IDC", "demoDetail.conclusion": "Висновок та підтвердження", "demoDetail.reportState": "Стан звіту", "demoDetail.references": "Демонстраційні довідкові орієнтири", "demoDetail.attachments": "Вкладення", "demoDetail.passport": "Публічний паспорт", "demoDetail.history": "Історія змін", "demoDetail.examinationDate": "Дата дослідження / оцінки", "demoDetail.shape": "Форма", "demoDetail.carat": "Вага (ct)", "demoDetail.color": "Колір", "demoDetail.clarity": "Чистота", "demoDetail.origin": "Походження", "demoDetail.treatment": "Ознаки обробки", "demoDetail.identificationLevel": "Рівень підтвердження", "demoDetail.identificationMethod": "Метод ідентифікації", "demoDetail.identificationConclusion": "Висновок щодо ідентифікації", "demoDetail.expertComment": "Коментар експерта",
    "analytics.totalInRange": "Усього у зрізі", "analytics.nonEmptyValues": "Непорожніх значень", "analytics.emptyValues": "Порожніх значень", "analytics.medianWords": "Медіана слів", "analytics.averageWords": "Середнє слів", "analytics.medianCharacters": "Медіана символів без пробілів", "analytics.averageCharacters": "Середнє символів без пробілів", "analytics.shortest": "Три найкоротші", "analytics.longest": "Три найдовші", "analytics.emptySamples": "До трьох порожніх", "analytics.noValues": "Непорожніх значень у цьому зрізі поки немає.", "analytics.emptyValue": "порожнє значення", "analytics.sampleMetrics": "{words} слів · {characters} символів без пробілів · {date}",
    "analytics.periodRange": "Поточний зріз: з {from} до {to}", "analytics.periodFrom": "Поточний зріз: від {from}", "analytics.periodTo": "Поточний зріз: до {to}", "analytics.periodAll": "Поточний зріз: за весь доступний час.",
    "analytics.from": "Від", "analytics.to": "До", "analytics.applyPeriod": "Застосувати період", "analytics.allTime": "За весь час",
    "analytics.title": "Аналітика", "analytics.subtitle": "Операційний огляд робочого процесу. Дані доступні лише адміністраторам.", "analytics.tabs": "Розділи аналітики", "analytics.stones": "Камені", "analytics.experts": "Експерти", "analytics.texts": "Тексти", "analytics.quality": "Операції та якість", "analytics.administrators": "Адміністратори", "analytics.providers": "Провайдери", "analytics.currencySources": "Валютні джерела", "analytics.stonesTitle": "Аналітика каменів", "analytics.expertsTitle": "Експерти та звіти", "analytics.textsTitle": "Текстові поля у звітах", "analytics.qualityTitle": "Операції та повнота даних", "analytics.administratorsTitle": "Перевірки адміністраторів", "analytics.providersTitle": "Операції та покриття постачальників", "analytics.currencyTitle": "Валютні джерела", "analytics.expertDialogTitle": "Деталі експерта", "analytics.providerDialogTitle": "Деталі постачальника", "analytics.close": "Закрити",
    "demo.previewTitle": "Показовий приватний перегляд", "demo.previewDescription": "DEMO-00999 містить синтетичні вкладення та внутрішній PDF без публічного ID, URL або QR-коду.", "demo.openPreview": "Відкрити DEMO-00999", "demo.currencyTitle": "Валютні джерела", "demo.workflowTitle": "Синтетичні експерти та звіти", "demo.narrativesTitle": "Синтетичні текстові поля", "demo.qualityTitle": "Синтетичні операції та повнота даних", "demo.administratorsTitle": "Синтетичні перевірки адміністраторів", "demo.providersTitle": "Синтетичні постачальники та орієнтири", "demo.somTitle": "Карта сегментів (SOM)", "demo.workflowDialogTitle": "Деталі синтетичного учасника", "demo.providerDialogTitle": "Деталі джерела", "demo.close": "Закрити",
    "demo.title": "Демо", "demo.subtitle": "Ізольований синтетичний набір для внутрішньої демонстрації інтерфейсу та технічних моделей.", "demo.tabs": "Розділи демо-набору", "demo.reports": "Демо-звіти", "demo.stones": "Камені", "demo.experts": "Експерти", "demo.texts": "Тексти", "demo.quality": "Операції та якість", "demo.administrators": "Адміністратори", "demo.providers": "Постачальники", "demo.currencySources": "Валютні джерела", "demo.syntheticNotice": "Ізольований внутрішній набір: не експертні, ринкові, продажні чи транзакційні дані.",
    "market.decisionApproveDescription": "Після затвердження цей незмінний знімок можна буде явно прикріпити до сумісного звіту.", "market.decisionRejectDescription": "Відхилений знімок не можна використати для ринкового орієнтира; самі дані знімка лишаються в історії.", "market.approvalComment": "Коментар до затвердження", "market.rejectionReason": "Причина відхилення", "market.approveSnapshot": "Затвердити знімок", "market.rejectSnapshot": "Відхилити знімок", "market.fetchingNbu": "Отримання офіційного курсу НБУ…", "market.nbuSaved": "Новий незмінний знімок офіційного курсу НБУ збережено.", "market.fetchingOpenfacet": "Отримання даних OpenFacet…", "market.candidateCreated": "Створено кандидат. Перевірте покриття та затвердьте його окремо.", "market.fetchFailed": "Не вдалося отримати дані постачальника.", "market.scheduleSaved": "Графік оновлення збережено.", "market.scheduleSaveFailed": "Не вдалося зберегти графік.", "market.policySaved": "Умови постачальника збережено.", "market.policySaveFailed": "Не вдалося зберегти умови постачальника.", "market.assignmentUpdated": "Призначення обмеженого пробного доступу оновлено.", "market.assignmentFailed": "Не вдалося змінити призначення.", "market.noPolicyEvents": "Для постачальника ще немає подій умов.", "market.policyEventsFailed": "Не вдалося завантажити журнал умов.", "market.signInAgain": "Потрібно увійти знову.", "market.referenceAttached": "Ринковий орієнтир успішно прикріплено.", "market.primaryMustBeEnabled": "Основний постачальник має входити до увімкненого набору.", "market.referencePolicySaved": "Налаштування системного довідкового орієнтиру збережено для майбутніх чернеток.", "market.referencePolicyFailed": "Не вдалося зберегти налаштування.", "market.snapshotApprovedMessage": "Знімок затверджено.", "market.snapshotRejectedMessage": "Знімок відхилено.", "market.decisionSaveFailed": "Не вдалося зберегти рішення.",
    "market.providersLegend": "Провайдери ринкових орієнтирів", "market.useFx": "Додавати еквівалент у UAH за офіційним курсом НБУ", "market.saveSettings": "Зберегти налаштування", "market.reportId": "Номер звіту", "market.approvedSnapshot": "Затверджений знімок", "market.applicability": "Підтвердження застосовності", "market.confirmAttach": "Підтверджую, що цей орієнтир застосовується лише як довідкове зіставлення, а не як експертна чи продажна ціна.", "market.attach": "Прикріпити ринковий орієнтир", "market.confirmDecision": "Підтвердити рішення", "market.comment": "Коментар", "market.optional": "Необов’язково", "market.cancel": "Скасувати", "market.confirm": "Підтвердити",
    "market.title": "Ринкові дані", "market.accessTerms": "Доступ і умови постачальників", "market.referencePolicy": "Системний довідковий орієнтир", "market.automaticRefresh": "Автоматичне оновлення", "market.providers": "Постачальники", "market.snapshotHistory": "Історія знімків", "market.operationLog": "Журнал операцій", "market.attachReference": "Прикріпити орієнтир до звіту",
    "market.noActiveProviders": "Активних постачальників ринкових орієнтирів немає.", "market.primaryForDashboard": "Основний для списку звітів", "market.accessMode": "Режим доступу", "market.disabled": "Вимкнено", "market.restrictedTrial": "Обмежений пробний доступ", "market.standardInternal": "Внутрішній стандартний", "market.dailyRequestLimit": "Денний ліміт запитів", "market.trialUntil": "Пробний доступ діє до (UTC)", "market.termsReference": "Посилання або коротка примітка до умов", "market.accessPolicyNote": "Дозволено лише природні камені й внутрішнє використання; публічне відображення та ML у цьому релізі вимкнені.", "market.assignedTrialAdministrators": "Призначені адміністратори з обмеженим пробним доступом:", "market.assignmentsTrialOnly": "Призначення доступні лише для обмеженого пробного доступу.", "market.showPolicyLog": "Показати журнал умов", "market.saveTerms": "Зберегти умови", "market.noSchedules": "Графіки ще не створені. Застосуйте міграцію 0013_market_provider_operations.", "market.enableScheduledRefresh": "Увімкнути планове оновлення", "market.scheduleTime": "Час (Europe/Kyiv)", "market.warnAfterHours": "Попереджати через, год.", "market.blockAfterHours": "Блокувати через, год.", "market.saveSchedule": "Зберегти графік", "market.invalidSchedule": "Перевірте час і пороги: блокування не може бути раніше попередження.",
    "app.title": "Diamant ID",
    "brand.home": "Головна Diamant ID",
    "navigation.primary": "Основна навігація",
    "navigation.verifyPassport": "Перевірити паспорт",
    "navigation.signIn": "Увійти",
    "navigation.allReports": "Всі звіти",
    "navigation.demo": "Демо",
    "navigation.experts": "Експерти",
    "navigation.references": "Довідники",
    "navigation.marketData": "Ринкові дані",
    "navigation.analytics": "Аналітика",
    "navigation.profile": "Профіль",
    "navigation.newReport": "Новий звіт",
    "auth.administrator": "Адміністратор",
    "auth.gemologist": "Експерт",
    "auth.user": "Користувач",
    "auth.signOut": "Вийти",
    "menu.open": "Відкрити меню",
    "session.saved": "Сеанс збережено. API тимчасово недоступний.",
    "session.retry": "Спробувати знову",
    "footer.privacy": "Політика конфіденційності",
    "footer.documentation": "Документація",
    "locale.switcher": "Мова",
    "locale.en": "Англійська",
    "locale.uk": "Українська",
    "landing.title": "Ідентифікація та оцінювання діамантів",
    "landing.subtitle": "Надійна перевірка паспортів та експертні звіти про діаманти — в одному робочому середовищі.",
    "landing.verifyPassport": "Перевірити паспорт",
    "landing.signIn": "Увійти для роботи зі звітами",
    "landing.heroAlt": "Діамант у гемологічному пінцеті",
    "landing.passportTitle": "Перевірка, якій можна довіряти",
    "landing.passportDescription": "Публічний паспорт відкривається за прямим посиланням, посиланням із QR-коду або кодом зі сторінки звіту. Тут введіть лише код; внутрішній номер звіту для цього не використовується.",
    "landing.passportCode": "Код публічного паспорта",
    "landing.passportPlaceholder": "Введіть код зі сторінки звіту",
    "landing.verify": "Перевірити",
    "landing.principles": "Можливості Diamant ID",
    "landing.expertReports": "Експертні звіти",
    "landing.expertReportsText": "Послідовна фіксація характеристик каменю та результатів оцінювання.",
    "landing.dataControl": "Контроль даних",
    "landing.dataControlText": "Чітке розмежування експертного висновку й розрахункового результату системи.",
    "landing.passportVerification": "Перевірка паспорта",
    "landing.passportVerificationText": "Окремий публічний маршрут для виданих звітів — після реалізації паспорта й QR.",
    "login.title": "Вхід у систему",
    "login.subtitle": "Будь ласка, авторизуйтесь",
    "login.username": "Логін",
    "login.password": "Пароль",
    "login.submit": "Увійти",
    "login.error": "Помилка входу: {message}",
    "passport.invalidInternalNumber": "Внутрішній номер звіту не є кодом публічного паспорта.",
    "passport.invalidCode": "Введіть код публічного паспорта зі сторінки звіту.",
    "wizard.notSpecified": "Не зазначено",
    "wizard.requiredStep": "Заповніть коректно обов’язкові поля кроку {step}.",
    "wizard.referencesFailed": "Не вдалося завантажити довідники: {message}",
    "wizard.noFile": "Файл не вибрано",
    "wizard.noMarketReference": "Немає доступного системного орієнтиру для введених характеристик.",
    "wizard.referenceSnapshot": "{provider} · знімок #{snapshot}. Значення буде зафіксовано під час збереження чернетки.",
    "wizard.snapshotValue": "{currency} {amount} · знімок #{snapshot}",
    "wizard.startedNew": "Почато нове незбережене введення.",
    "wizard.restored": "Незбережене введення відновлено. Вкладення додайте повторно.",
    "wizard.leaveNavigation": "Введені дані ще не стали чернеткою на сервері. Вони залишаться лише в цій вкладці, і після повернення їх можна буде явно відновити.",
    "wizard.leaveLogout": "Введені дані ще не стали чернеткою на сервері. Після виходу вони залишаться лише в цій вкладці та будуть доступні для явного відновлення лише після повторного входу цим самим обліковим записом.",
    "wizard.signOut": "Вийти",
    "wizard.go": "Перейти",
    "wizard.saving": "Збереження чернетки…",
    "wizard.saveFailed": "Не вдалося зберегти чернетку: {message}",
    "wizard.pageTitle": "Новий звіт",
    "wizard.pageSubtitle": "Створення чернетки експертного звіту про камінь.",
    "wizard.steps": "Кроки створення звіту",
    "wizard.step1Short": "1. Основне",
    "wizard.step1": "1. Ідентифікація та 4C",
    "wizard.step2Short": "2. Геометрія",
    "wizard.step2": "2. Геометрія (IDC)",
    "wizard.step3Short": "3. Висновок",
    "wizard.step3": "3. Висновок та медіа",
    "wizard.identification": "Ідентифікація",
    "wizard.nextReportId": "Наступний номер звіту",
    "wizard.idServerAssigned": "Номер остаточно присвоюється сервером під час збереження.",
    "wizard.examinationDate": "Дата дослідження / оцінки",
    "wizard.shape": "Форма",
    "wizard.origin": "Походження",
    "wizard.fourCs": "Характеристики 4C",
    "wizard.caratWeight": "Вага",
    "wizard.color": "Колір",
    "wizard.clarity": "Чистота",
    "wizard.loadingReference": "Завантаження довідника…",
    "wizard.dimensions": "Розміри", "wizard.length": "Довжина (мм)", "wizard.width": "Ширина (мм)", "wizard.depth": "Висота (мм)",
    "wizard.cuttingParameters": "Параметри огранювання (IDC)", "wizard.table": "Таблиця (%)", "wizard.totalDepth": "Загальна глибина (%)",
    "wizard.crownAngle": "Кут корони (°)", "wizard.pavilionAngle": "Кут павільйону (°)", "wizard.girdle": "Товщина рундиста", "wizard.culet": "Калета",
    "wizard.finish": "Якість обробки", "wizard.polish": "Поліровка", "wizard.symmetry": "Симетрія", "wizard.fluorescence": "Флуоресценція",
    "wizard.expertConclusion": "Висновок експерта", "wizard.treatment": "Ознаки обробки", "wizard.identificationStatus": "Рівень підтвердження",
    "wizard.identificationMethod": "Метод ідентифікації", "wizard.identificationConclusion": "Висновок щодо ідентифікації", "wizard.expertComment": "Коментар експерта",
    "wizard.media": "Медіа", "wizard.plotting": "Схема дефектів", "wizard.stonePhoto": "Фото каменя", "wizard.chooseFile": "Вибрати файл",
    "wizard.privateMediaHelp": "JPEG, PNG або WebP, до 10 МБ. Зберігається приватно.", "wizard.back": "Назад", "wizard.clearEntry": "Очистити введення", "wizard.saveDraft": "Зберегти чернетку", "wizard.next": "Далі",
    "wizard.restoreTitle": "Відновити незбережене введення?", "wizard.restoreDescription": "Знайдено незбережені дані цієї вкладки. Вони не були надіслані на сервер.", "wizard.restoreMedia": "Вкладення не відновлюються — після відновлення додайте файли повторно.", "wizard.startNew": "Почати заново", "wizard.restore": "Відновити",
    "wizard.clearTitle": "Очистити незбережене введення?", "wizard.close": "Закрити", "wizard.clearDescription": "Дані цієї вкладки буде видалено з форми й локального сховища. Це не змінить жодного збереженого звіту.", "wizard.cancel": "Скасувати", "wizard.stay": "Залишитися", "wizard.leaveTitle": "Залишити майстер?",
    "detail.privateReport": "Приватний звіт", "detail.loadingReport": "Завантаження звіту…", "detail.subtitle": "Дані, висновок експерта, вкладення та історія змін.", "detail.backToReports": "До всіх звітів", "detail.editDraft": "Редагувати чернетку", "detail.saveChanges": "Зберегти зміни", "detail.reportState": "Стан звіту", "detail.transitionReason": "Коментар до зміни статусу", "detail.transitionReasonPlaceholder": "Необов’язково, але бажано для повернення чи анулювання", "detail.narrativeQuality": "Перевірка текстових полів", "detail.narrativeHelp": "Автоматичні сигнали заповнення не оцінюють професійний висновок і не блокують збереження.", "detail.loading": "Завантаження…", "detail.marketReference": "Довідковий ринковий орієнтир", "detail.marketReferenceHelp": "Ринковий орієнтир не є експертною, продажною чи транзакційною ціною.", "detail.attachments": "Вкладення", "detail.history": "Історія змін",
    "detail.stonePhoto": "Фото каменю", "detail.plottingDiagram": "Схема огранювання (plotting)", "detail.eventCreated": "Створено", "detail.eventUpdated": "Дані чернетки оновлено", "detail.eventStatusChanged": "Статус змінено", "detail.eventPassportPublished": "Публічний паспорт опубліковано", "detail.eventPassportReissued": "Публічний паспорт перевипущено", "detail.eventPassportRevoked": "Публічний паспорт відкликано", "detail.eventMediaPublished": "Вкладення опубліковано в паспорті", "detail.eventMediaUnpublished": "Вкладення прибрано з паспорта", "detail.eventSystemReference": "Системний довідковий орієнтир додано", "detail.eventAdminReference": "Довідковий орієнтир підтверджено адміністратором", "detail.eventLegacyImport": "Імпортовано з попередньої бази", "detail.notConfirmed": "Не підтверджено", "detail.chooseColor": "Оберіть колір", "detail.chooseClarity": "Оберіть чистоту", "detail.chooseValue": "Оберіть значення", "detail.chooseGrade": "Оберіть оцінку", "detail.notSpecified": "Не задано", "detail.noEvents": "Подій ще немає.",
    "detail.publicPassport": "Публічний паспорт", "detail.passportIssuedOnly": "Доступний лише для виданого звіту.", "detail.passportCode": "Код паспорта", "detail.openPublicPassport": "Відкрити публічний паспорт", "detail.passportQrAlt": "QR-код публічного паспорта", "detail.publishPassport": "Опублікувати паспорт", "detail.copyLink": "Скопіювати посилання", "detail.copyCode": "Скопіювати код", "detail.downloadPdf": "Завантажити PDF", "detail.reissueLink": "Перевипустити посилання", "detail.revokePublication": "Відкликати публікацію", "detail.confirmAttachmentPublication": "Підтвердити публікацію вкладення", "detail.confirm": "Підтвердити", "detail.attachment": "Вкладення", "detail.removeFromPassport": "Прибрати з паспорта", "detail.publishInPassport": "Опублікувати в паспорті", "detail.publishedInPassport": "Опубліковано в паспорті", "detail.publishing": "Публікація…", "detail.publishingPassport": "Публікація паспорта…", "detail.passportPublished": "Паспорт опубліковано.", "detail.publishPassportFailed": "Не вдалося опублікувати паспорт.", "detail.passportNotPublished": "Паспорт ще не опубліковано.", "detail.publicLinkCopied": "Публічне посилання скопійовано.", "detail.copyLinkFailed": "Не вдалося скопіювати посилання.", "detail.passportCodeCopied": "Код публічного паспорта скопійовано.", "detail.copyCodeFailed": "Не вдалося скопіювати код.", "detail.generatingPassportPdf": "Формування PDF-паспорта…", "detail.passportPdfDownloaded": "PDF-паспорт завантажено.", "detail.passportPdfFailed": "Не вдалося сформувати PDF-паспорт.", "detail.reissueConfirm": "Перевипустити паспорт? Попередній код, посилання й QR перестануть працювати.", "detail.reissuingPassport": "Перевипуск паспорта…", "detail.passportReissued": "Створено новий код, посилання та QR-код.", "detail.reissueFailed": "Не вдалося перевипустити посилання.", "detail.revokeConfirm": "Відкликати публічний паспорт? Код, посилання й QR одразу перестануть працювати.", "detail.revokingPassport": "Відкликання публікації…", "detail.passportRevoked": "Публікацію паспорта відкликано.", "detail.revokeFailed": "Не вдалося відкликати паспорт.", "detail.sendForReview": "Передати на перевірку", "detail.returnToDraft": "Повернути в чернетку", "detail.issueReport": "Видати звіт", "detail.voidReport": "Анулювати", "detail.issueNeedsProportions": "Для видачі потрібна експертна оцінка пропорцій.", "detail.reviewNeedsProportions": "Для видачі поверніть звіт у чернетку та оберіть експертну оцінку пропорцій.", "detail.draftEditHelp": "Чернетку може редагувати її автор або адміністратор.", "detail.lockedAfterReview": "Після передачі на перевірку поля звіту заблоковані; переходи контролює сервер.",
    "detail.noNarrativeWarnings": "Пояснюваних сигналів заповнення зараз немає.", "detail.noPrivateAttachments": "Приватних вкладень немає.", "detail.noMarketReferences": "Системного або підтвердженого ринкового орієнтира ще немає.", "detail.marketReferenceDescription": "Кожен орієнтир належить окремому провайдеру та знімку. Системний орієнтир формується автоматично з останнього затвердженого знімка; підтверджений орієнтир окремо перевіряє адміністратор. Орієнтири не є експертною, продажною чи транзакційною ціною.", "detail.previousReferencesCollapsed": "Поточний запис відкритий; попередні збережені орієнтири згорнуті.", "detail.confirmation": "Підтвердження", "detail.systemReferenceNote": "Автоматично розраховано за останнім затвердженим знімком {provider}; застосовність не підтверджена адміністратором.", "detail.copyFailed": "Не вдалося скопіювати дані", "detail.passportPublishedDescription": "Паспорт опубліковано. Його можна перевірити за посиланням, QR або кодом; перевипуск одразу відкликає попередні дані доступу.", "detail.passportStateLoadFailed": "Не вдалося завантажити стан публікації.", "detail.reportIdMissing": "Не вказано номер звіту.", "detail.publishAttachmentDescription": "Зображення стане доступним у публічному паспорті лише за чинним посиланням або QR-кодом. Воно не потрапляє до PDF.", "detail.unpublishAttachmentDescription": "Зображення перестане відображатися у публічному паспорті. Приватне вкладення у звіті буде збережено.", "detail.createdAt": "Створено: {date}", "detail.systemSummary": "Системний IDC: Proportions {proportions}, Final Cut {cut}.", "detail.expertSummary": "Експертні grades: Proportions {proportions}, підсумковий Cut {cut}.", "detail.narrativeUnavailable": "Текстові метадані тимчасово недоступні.", "detail.marketReferencesLoadFailed": "Не вдалося завантажити ринковий орієнтир.", "detail.statusChanging": "Зміна статусу…", "detail.statusUpdated": "Статус звіту оновлено.", "detail.statusUpdateFailed": "Не вдалося змінити статус.", "detail.reportForbidden": "У вас немає доступу до цього звіту.", "detail.reportLoadFailed": "Не вдалося завантажити приватний звіт.", "detail.pagePreparationFailed": "Не вдалося підготувати сторінку звіту. Сеанс збережено — оновіть сторінку після відновлення API.", "detail.attachmentPublished": "Вкладення опубліковано в паспорті.", "detail.attachmentUnpublished": "Вкладення прибрано з паспорта.", "detail.attachmentVisibilityFailed": "Не вдалося змінити видимість вкладення.", "detail.savingChanges": "Збереження змін…", "detail.changesSaved": "Зміни чернетки збережено.", "detail.saveChangesFailed": "Не вдалося зберегти зміни.",
    "dashboard.statusDraft": "Чернетка", "dashboard.statusReview": "На перевірці", "dashboard.statusIssued": "Видано", "dashboard.statusVoid": "Анульовано", "dashboard.notSold": "Не продано", "dashboard.sold": "Продано",
    "dashboard.view": "Переглянути", "dashboard.edit": "Редагувати", "dashboard.editDraftOnly": "Редагування доступне лише для чернетки", "dashboard.print": "Друк", "dashboard.loading": "Завантаження звітів…", "dashboard.empty": "Звітів за поточними умовами не знайдено.", "dashboard.loadFailed": "Не вдалося завантажити звіти. Оновіть сторінку або спробуйте пізніше.",
    "dashboard.title": "Всі звіти", "dashboard.subtitle": "Управління сертифікатами та оцінками.", "dashboard.newReport": "Новий звіт", "dashboard.search": "Пошук за номером звіту", "dashboard.filters": "Фільтри", "dashboard.allReportStatuses": "Усі статуси звіту", "dashboard.allSaleStatuses": "Усі статуси продажу", "dashboard.allExperts": "Усі експерти",
    "dashboard.reportStatus": "Статус звіту", "dashboard.saleStatus": "Статус продажу", "dashboard.expert": "Експерт", "dashboard.shape": "Форма", "dashboard.any": "Будь-яка", "dashboard.carat": "Вага (карат)", "dashboard.from": "Від", "dashboard.to": "До", "dashboard.color": "Колір", "dashboard.clarity": "Чистота", "dashboard.cut": "Якість (Cut)", "dashboard.referenceUsd": "Довідковий орієнтир (USD)", "dashboard.createdFrom": "Дата створення: від", "dashboard.createdTo": "Дата створення: до", "dashboard.apply": "Застосувати", "dashboard.clear": "Очистити", "dashboard.referenceNote": "Довідкові орієнтири (USD) формуються для нових або змінених чернеток за налаштованим провайдером (поточне джерело — OpenFacet). Позначка SYS означає системний довідковий орієнтир, ADM — орієнтир, застосовність якого підтвердив адміністратор; поруч завжди вказано джерело. Це не експертна, продажна чи транзакційна ціна; еквівалент у UAH додається лише за увімкненим курсом НБУ та фіксується під час створення.",
    "dashboard.reportId": "ID звіту", "dashboard.date": "Дата", "dashboard.caratColumn": "Вага (ct)", "dashboard.priceUsd": "Ціна (USD)", "dashboard.actions": "Дії", "dashboard.pagination": "Пагінація звітів", "dashboard.sortReportId": "Сортувати за ID звіту", "dashboard.sortDate": "Сортувати за датою", "dashboard.sortShape": "Сортувати за формою", "dashboard.sortCarat": "Сортувати за вагою", "dashboard.sortColor": "Сортувати за кольором", "dashboard.sortClarity": "Сортувати за чистотою", "dashboard.sortCut": "Сортувати за Cut", "dashboard.sortPrice": "Сортувати за довідковим орієнтиром", "dashboard.sortReportStatus": "Сортувати за статусом звіту", "dashboard.sortSaleStatus": "Сортувати за статусом продажу",
    "dashboard.openActions": "Відкрити дії для звіту {reportId}", "dashboard.referenceTypeDemo": "Демонстраційний орієнтир", "dashboard.referenceTypeSystem": "Системний довідковий орієнтир", "dashboard.referenceTypeAdmin": "Підтверджений довідковий орієнтир", "dashboard.referenceExplanation": "Пояснення ринкового орієнтира звіту {reportId}", "dashboard.referenceType": "Тип", "dashboard.provider": "Постачальник", "dashboard.providerSnapshot": "Знімок постачальника", "dashboard.observed": "Отримано", "dashboard.equivalent": "Еквівалент", "dashboard.nbuRate": "Курс НБУ", "dashboard.notAvailableForDemo": "Не передбачено для синтетичного демо", "dashboard.notCalculatedForDemo": "Не розраховується для синтетичного демо", "dashboard.notApplicableForDemo": "Не застосовується для синтетичного демо", "dashboard.nbuRateValue": "{rate} UAH/USD · {date} · знімок #{snapshot}", "dashboard.otherReferences": "Інші доступні орієнтири:", "dashboard.demoReferenceWarning": "Синтетичне демонстраційне значення; не є ринковою, експертною, продажною чи транзакційною ціною.", "dashboard.systemReferenceWarning": "Розраховано системою за останнім затвердженим знімком; не є експертною, продажною чи транзакційною ціною.", "dashboard.adminReferenceWarning": "Застосовність підтверджена адміністратором; не є експертною, продажною чи транзакційною ціною.", "dashboard.openPrivateReport": "Відкрити приватний перегляд звіту", "dashboard.firstPage": "На першу сторінку", "dashboard.previousPage": "На попередню сторінку", "dashboard.nextPage": "На наступну сторінку", "dashboard.lastPage": "На останню сторінку",
    "profile.title": "Профіль", "profile.subtitle": "Керуйте власними даними та паролем.", "profile.details": "Дані профілю", "profile.username": "Логін", "profile.role": "Роль", "profile.firstName": "Ім’я", "profile.lastName": "Прізвище", "profile.middleName": "По батькові", "profile.saveDetails": "Зберегти дані", "profile.changePassword": "Змінити пароль", "profile.currentPassword": "Поточний пароль", "profile.newPassword": "Новий пароль", "profile.confirmPassword": "Підтвердіть новий пароль", "profile.submitPassword": "Змінити пароль", "profile.demoAccess": "Доступ до «Демо»", "profile.demoAccessHelp": "Ізольований синтетичний набір для внутрішньої демонстрації. Він не містить реальних звітів, ринкових даних або публічних паспортів.", "profile.enableDemoAccess": "Увімкнути доступ до «Демо» для мого облікового запису", "profile.saveAccess": "Зберегти доступ", "profile.partnerControls": "Доступ до керування партнерськими даними", "profile.partnerControlsHelp": "Цей режим відкриває лише внутрішні інструменти керування умовами постачальників. Він не вмикає зовнішнього постачальника, не видає ключів і не надає пробного доступу.", "profile.enablePartnerControls": "Увімкнути доступ до керування партнерськими даними для мого облікового запису", "profile.saved": "Дані профілю збережено.", "profile.demoEnabled": "Доступ до «Демо» увімкнено.", "profile.demoDisabled": "Доступ до «Демо» вимкнено.", "profile.partnerEnabled": "Доступ до керування партнерськими даними увімкнено.", "profile.partnerDisabled": "Доступ до керування партнерськими даними вимкнено.", "profile.passwordMismatch": "Новий пароль і підтвердження не збігаються.", "profile.passwordChanged": "Пароль змінено.",
    "experts.deactivate": "Деактивувати", "experts.activate": "Активувати", "experts.adminOnly": "Ця сторінка доступна лише адміністратору.", "experts.username": "Логін", "experts.name": "Ім’я", "experts.role": "Роль", "experts.active": "Активний", "experts.inactive": "Неактивний", "experts.state": "Стан", "experts.actions": "Дії", "experts.edit": "Змінити", "experts.created": "Експерта створено.", "experts.updated": "Обліковий запис оновлено.", "experts.stateUpdated": "Стан облікового запису оновлено.",
    "experts.title": "Експерти", "experts.subtitle": "Створюйте облікові записи, змінюйте ролі та безпечно деактивуйте доступ.", "experts.new": "Новий експерт", "experts.temporaryPassword": "Тимчасовий пароль", "experts.create": "Створити експерта", "experts.accounts": "Облікові записи", "experts.accountsHelp": "Деактивація не видаляє звіти, паспорти або історію змін. Власний обліковий запис деактивувати не можна.", "experts.search": "Пошук облікових записів", "experts.searchPlaceholder": "Пошук за логіном або ім’ям", "experts.pagination": "Пагінація облікових записів", "experts.editAccount": "Редагувати обліковий запис", "experts.close": "Закрити", "experts.newTemporaryPassword": "Новий тимчасовий пароль", "experts.passwordHelp": "Залиште порожнім, якщо пароль не потрібно змінювати.", "experts.save": "Зберегти зміни",
    "references.title": "Довідники", "references.subtitle": "Поточні значення, які сервер надає формам звітів.", "references.help": "Редагування з причиною, документом-джерелом і версіями для нових звітів заплановане окремою задачею 105. Поточні дані лише для перегляду.", "references.shape": "Форма", "references.origin": "Походження", "references.treatment": "Ознаки обробки", "references.identificationStatus": "Рівень підтвердження", "references.marketStatus": "Комерційний стан", "references.reportStatus": "Статус звіту", "references.girdle": "Товщина рундиста", "references.culet": "Калета", "references.code": "Код", "references.value": "Значення",
    "market.snapshotCandidate": "Кандидат", "market.snapshotApproved": "Затверджено", "market.snapshotRejected": "Відхилено", "market.fresh": "Актуальні", "market.warning": "Потребують оновлення", "market.stale": "Застарілі", "market.missing": "Знімків немає", "market.operationSuccess": "Успішно", "market.operationNoChange": "Без змін", "market.operationFailed": "Помилка", "market.operationSkipped": "Пропущено", "market.dataState": "Стан даних", "market.lastRetrieved": "останнє отримання", "market.documentation": "Документація", "market.terms": "Умови використання", "market.refreshNow": "Оновити зараз", "market.fetchCandidate": "Отримати кандидат", "market.noSnapshots": "Знімків ще немає.", "market.sourceMethodology": "Методологія джерела", "market.decision": "Рішення", "market.approve": "Затвердити", "market.reject": "Відхилити", "market.manual": "Вручну", "market.scheduled": "За графіком", "market.attempt": "спроба", "market.noOperations": "Операцій ще не було.", "market.selectSnapshot": "Оберіть знімок", "market.noApprovedSnapshots": "Немає затверджених знімків",
    "narrative.fields": "Текстові поля", "narrative.identificationMethod": "Метод ідентифікації", "narrative.identificationConclusion": "Висновок щодо ідентифікації", "narrative.expertComment": "Коментар експерта", "narrative.statusTransition": "Подія зміни статусу без коментаря", "narrative.show": "Показувати:", "narrative.showFields": "Показувати текстові поля", "narrative.empty": "Порожні", "narrative.filled": "Заповнені", "narrative.demoNote": "Синтетичний життєвий цикл не має текстових коментарів; цю опцію не моделюємо.", "narrative.realNote": "Подія зміни статусу перевіряється у вибраному зрізі дат.",
  },
};

let activeLocale = DEFAULT_LOCALE;

function normalizeLocale(value) {
  return SUPPORTED_LOCALES.includes(value) ? value : DEFAULT_LOCALE;
}

function interpolate(message, values) {
  return message.replace(/\{(\w+)\}/g, (_match, name) => String(values[name] ?? `{${name}}`));
}

export function validateCatalogs() {
  const englishKeys = Object.keys(catalogs.en).sort();
  for (const locale of SUPPORTED_LOCALES) {
    const localeKeys = Object.keys(catalogs[locale]).sort();
    if (englishKeys.length !== localeKeys.length || englishKeys.some((key, index) => key !== localeKeys[index])) {
      throw new Error(`i18n catalog keys do not match for locale ${locale}.`);
    }
    for (const key of localeKeys) {
      if (!catalogs[locale][key]?.trim()) throw new Error(`i18n catalog value is missing for ${locale}.${key}.`);
    }
  }
}

export function getLocale() {
  return activeLocale;
}

export function resolveLocale(search = globalThis.window?.location?.search ?? "", storedLocale = globalThis.localStorage?.getItem(LOCALE_STORAGE_KEY)) {
  const requestedLocale = new URLSearchParams(search).get("lang");
  if (SUPPORTED_LOCALES.includes(requestedLocale)) return requestedLocale;
  return normalizeLocale(storedLocale);
}

export function t(key, values = {}) {
  const message = catalogs[activeLocale]?.[key];
  if (!message) throw new Error(`Missing i18n key: ${key}`);
  return interpolate(message, values);
}

export function formatDate(value, options = {}) {
  return new Intl.DateTimeFormat(activeLocale === "uk" ? "uk-UA" : "en-US", options).format(value);
}

export function formatNumber(value, options = {}) {
  return new Intl.NumberFormat(activeLocale === "uk" ? "uk-UA" : "en-US", options).format(value);
}

export function formatCurrency(value, currency, options = {}) {
  return formatNumber(value, { style: "currency", currency, ...options });
}

export function applyTranslations(root = globalThis.document) {
  if (!root) return;
  root.documentElement?.setAttribute("lang", activeLocale);
  if (root.title !== undefined) root.title = t("app.title");
  root.querySelectorAll?.("[data-i18n]").forEach((node) => { node.textContent = t(node.dataset.i18n); });
  root.querySelectorAll?.("[data-i18n-placeholder]").forEach((node) => { node.placeholder = t(node.dataset.i18nPlaceholder); });
  root.querySelectorAll?.("[data-i18n-alt]").forEach((node) => { node.alt = t(node.dataset.i18nAlt); });
  root.querySelectorAll?.("[data-i18n-aria-label]").forEach((node) => { node.setAttribute("aria-label", t(node.dataset.i18nAriaLabel)); });
  root.querySelectorAll?.("[data-locale-switch]").forEach((node) => {
    const isActive = node.dataset.localeSwitch === activeLocale;
    node.setAttribute("aria-pressed", String(isActive));
    node.classList.toggle("is-active", isActive);
  });
}

export function setLocale(locale, { updateUrl = true } = {}) {
  activeLocale = normalizeLocale(locale);
  globalThis.localStorage?.setItem(LOCALE_STORAGE_KEY, activeLocale);
  if (updateUrl && globalThis.window?.location && globalThis.window?.history?.replaceState) {
    const url = new URL(globalThis.window.location.href);
    url.searchParams.set("lang", activeLocale);
    globalThis.window.history.replaceState(globalThis.window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
  }
  applyTranslations();
  const LocaleChangeEvent = globalThis.window?.CustomEvent ?? globalThis.CustomEvent;
  if (LocaleChangeEvent) globalThis.window?.dispatchEvent?.(new LocaleChangeEvent("diamant:locale-change", { detail: { locale: activeLocale } }));
  return activeLocale;
}

export function initializeI18n() {
  validateCatalogs();
  activeLocale = resolveLocale();
  applyTranslations();
  return activeLocale;
}

export const i18nCatalogs = catalogs;
